// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StorehouseOfAppliances.Models;

public partial class Pallet
{
    public int Id { get; set; }

    public decimal Width { get; set; }

    public decimal Height { get; set; }

    public decimal Length { get; set; }

    public decimal? Volume { get; set; }

    public decimal Weight { get; set; }
}