// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StorehouseOfAppliances.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Supplier { get; set; }

    public decimal Weight { get; set; }

    public decimal Volume { get; set; }

    public int Quantity { get; set; }
}