// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace StorehouseOfAppliances.Models;

public partial class StorehouseOfAppliancesContext : DbContext
{
    public StorehouseOfAppliancesContext()
    {
    }

    public StorehouseOfAppliancesContext(DbContextOptions<StorehouseOfAppliancesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Pallet> Pallets { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=NEXT\\SQLEXPRESS;Initial Catalog=StorehouseOfAppliances;Integrated Security=True;encrypt=false");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Pallet>(entity =>
        {
            entity.ToTable("Pallet");

            entity.Property(e => e.Height).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.Length).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.Volume)
                .HasComputedColumnSql("(([Height]*[Width])*[Length])", false)
                .HasColumnType("decimal(38, 6)");
            entity.Property(e => e.Weight).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.Width).HasColumnType("decimal(18, 3)");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable("Product");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Supplier)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Volume).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.Weight).HasColumnType("decimal(18, 3)");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Role__3214EC07A3D82651");

            entity.ToTable("Role");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("User");

            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Image).IsRequired();
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Login)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Password).IsRequired();
            entity.Property(e => e.Patronymic).HasMaxLength(50);
            entity.Property(e => e.TelephoneNumber)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_User_Role");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}